import type { Metadata } from 'next'
import './globals.css'

import Header from '@/components/layouts/header'
import Footer from '@/components/layouts/footer'
import { Providers } from '@/components/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='kr' suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <div className='pt-[calc(var(--header-height)+1.5rem)]'>{children}</div>

          <Footer />
        </Providers>
      </body>
    </html>
  )
}
