version: '3'

services:
    mariadb:
        image: mariadb:latest # 이 줄을 추가하세요
        container_name: nest-mariadb-local
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/mariadb/init:/docker-entrypoint-initdb.d

volumes:
    mariadb_data:
